version: '3'

networks:
  api:

services:
  web:
    image: youtube-search-web
    container_name: youtube-search-web
    restart: always
    build: .
    ports:
      - 8000:5000
    volumes:
      - .:/code
    networks:
      - api
    env_file:
      - .env

  redis:
    container_name: youtube-search-redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - api
    env_file:
      - .env

  celery:
    container_name: youtube-search-celery
    restart: always
    image: youtube-search-web
    command: celery -A youtube_search worker -l info --uid uwsgi
    volumes:
      - .:/code
    networks:
      - api
    env_file:
      - .env


  celery-beat:
    container_name: youtube-search-celery-beat
    image: youtube-search-web
    restart: always
    command: celery -A youtube_search beat -l info --uid uwsgi --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    networks:
      - api
    env_file:
      - .env


