# Generated by Django 2.1.7 on 2019-03-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_word_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='word_id',
            new_name='word',
        ),
    ]
