# Generated by Django 2.1.7 on 2019-03-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190327_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='key_word',
            field=models.CharField(max_length=64),
        ),
    ]
