# Generated by Django 2.1.7 on 2019-03-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190327_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='word',
            new_name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='videos',
            field=models.ManyToManyField(to='api.Video'),
        ),
    ]
